name: JasonDilworth
favicon: null
layout_spectrum: 0.3039272336754948
typography_spectrum: 0.6197330120485276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23668926185928285
  lightness: 0.009582296945154667
  saturation: 0.8885512517299503
  rhythmicContrast: 0.47324296389706433
purpose: []
