name: JasonDilworth
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6fbe44'
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#00ff00'
  brandStrength: 0.23668926185928285
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
